/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: operations["AppController_getHello"];
  };
  "/auth": {
    post: operations["AuthController_login"];
  };
  "/auth/callback": {
    get: operations["AuthController_callback"];
  };
  "/auth/refresh": {
    post: operations["AuthController_refresh"];
  };
  "/users": {
    get: operations["UsersController_findAll"];
    post: operations["UsersController_create"];
  };
  "/users/{id}": {
    get: operations["UsersController_findOne"];
    post: operations["UsersController_update"];
    delete: operations["UsersController_remove"];
  };
  "/chat/setAPIKey/{field}": {
    post: operations["ChatController_setKey"];
  };
  "/chat/conversations/{user}": {
    get: operations["ChatController_getConversation"];
  };
  "/chat/conversations/{user}/{conversation_id}": {
    get: operations["ChatController_getConversationMessages"];
    delete: operations["ChatController_deleteConversation"];
  };
  "/chat/conversations/{user}/{conversation_id}/{name}": {
    post: operations["ChatController_renameConversation"];
  };
  "/chat/sse": {
    get: operations["ChatController_sse"];
  };
  "/chat/{action}": {
    post: operations["ChatController_chatAction"];
  };
  "/chat/conversations/file/upload": {
    post: operations["ChatController_uploadFile"];
  };
  "/chat/conversations/response/regenerate": {
    post: operations["ChatController_Regenerate"];
  };
  "/chat/conversations/response/details": {
    post: operations["ChatController_ShowMoreOrLessDetails"];
  };
  "/chat/conversations/response/rating": {
    post: operations["ChatController_rateMessage"];
  };
  "/chat/conversations/response/stop": {
    post: operations["ChatController_stopGeneration"];
  };
  "/payments": {
    post: operations["PaymentsController_initPayment"];
  };
  "/payments/verify": {
    get: operations["PaymentsController_verifyPayment"];
  };
}


export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    AuthRequestDto: Record<string>;
    refreshTokenDto: Record<string>;
    UpdateUserDto: Record<string>;
    CreatePaymentDto: Record<string>;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  AppController_getHello: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AuthController_login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthRequestDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_callback: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AuthController_refresh: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["refreshTokenDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  UsersController_findAll: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  UsersController_create: {
    requestBody: {
      content: {
        "application/json": string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  UsersController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  UsersController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  UsersController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ChatController_setKey: {
    parameters: {
      path: {
        field: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ChatController_getConversation: {
    parameters: {
      path: {
        user: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ChatController_getConversationMessages: {
    parameters: {
      path: {
        user: string;
        conversation_id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ChatController_deleteConversation: {
    parameters: {
      path: {
        user: string;
        conversation_id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ChatController_renameConversation: {
    parameters: {
      path: {
        user: string;
        conversation_id: string;
        name: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ChatController_sse: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  ChatController_chatAction: {
    parameters: {
      path: {
        action: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ChatController_uploadFile: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  ChatController_Regenerate: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  ChatController_ShowMoreOrLessDetails: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  ChatController_rateMessage: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  ChatController_stopGeneration: {
    responses: {
      201: {
        content: never;
      };
    };
  };

  PaymentsController_initPayment: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePaymentDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PaymentsController_verifyPayment: {
    parameters: {
      query: {
        paymentId: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
}
